% Store the students information into a structure array
data=struct('Student1', ...
    struct('Name','John Smith','SSN','392-77-1786','Email','smith@info.edu','Tests',[67 75 85]),'Student2', ...
    struct('Name','Mary Jones','SSN','431-56-9832','Email','mary@info.edu','Tests',[84 78 93]),'Student3', ...
    struct('Name','Alex Sam','SSN','692-87-1897','Email','alex@info.edu','Tests',[76 65 90]));



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
T=table([data.Student1.Name;data.Student2.Name;data.Student3.Name],...
    [data.Student1.SSN;data.Student2.SSN;data.Student3.SSN],...
    [data.Student1.Email;data.Student3.Email;data.Student3.Email]);
    %vertcat(data.Student1.Tests,data.Student1.Tests;data.Student1.Tests));